site_name: HT16 Planung Homepage 2017

pages:
    - Home: 'index.md'
    - Bestand: 'bestand.md'
    - Neuplanung:
        - Ziele: 'ziele.md'
        - Inhaltstypen: 'inhaltstypen.md'
        - Inhaltselemente: 'inhaltselemente.md'
        - Architektur: 'infoarchitektur.md'
        - Design: 'design.md'
